version: "3"
services:
  pgsql:
    container_name: pgsql 
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_store:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=VKyXzuCgM2yr

volumes:
  pg_store:
    external: true
