version: "3"
services:
  # ... mongodb ...
  mongodb:
    image: "mongo"
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    volumes:
      - mongo_store:/data/db
    command: mongod
volumes:
  mongo_store:
    driver: local
