version: '3'
services:
  nsqlookupd:
    image: nginx:stable-alpine
    container_name: staticserver
    restart: always
    ports:
      - "3333:80"
    volumes:
      - './static.conf:/etc/nginx/conf.d/default.conf' #nginx配置文件
      - './staticfiles/:/www/data/'
